### ISSUE TITLE
Styles on Curriculum page

### ISSUE THREAD

**Issue by reedeth** [scholarslab/clockwork#43]
This is a big one because there are a lot of places to implement, but I think we would benefit a lot from varying the style of different sections of text on the Curriculum page. We have so much good text here I want to make sure it is as engaging as possible! 

The accordion looks great and is very helpful in navigating the large amount of text on the page, but I think even inside these accordion-ed sections it would be good to vary the style of certain sections to make them easier to read and understand. Right now the only formatting we have that does this is the use of bold, lists, and new paragraphs. The marginalia is something we could use more of to do this, but I'm sure we could come up with more ways. 

Some examples of where it might help:
1. In the Introduction, we could change the style of "BIG QUESTIONS AT THE BEGINNING" and the text that follows instead of capitalizing it.
2. We could do the same for the paragraph following "ClockWork:" also in the Introduction tab.
3. There's a ton of information in the "How Did We Select Our Data" - would be great to break that up somehow by highlighting different kinds of thoughts with different styles.
4. Same goes for the annotated bibliography - I think that section would benefit a lot from some new stylings to differentiate its 'bibliography-ness' from other kinds of text

**Comment by bremend** [comment]
Agreed. Working on incorporating these changes. 

Also: 
1. What do folks think about using the orange highlight color for drop down bars, rather than blue? 
2. Would it be possible to keep multiple tabs expanded simultaneously?
3. Does it make more sense to do separate boxes (like the yellow ones we currently have) on the side, or to keep the information in a linear (top>bottom) format but shade paragraphs to punch them out?

**Comment by erochest** [comment]
Will be covered by #64.
